import os

ORIGEN_X_VENTANA = 200
ORIGEN_Y_VENTANA = 100
ANCHO_VENTANA = 800
ALTO_VENTANA = 600

ANCHO_JUGADOR = 30
ALTO_JUGADOR = 35
DIRECCION_SPRITE = os.path.join('utiles', 'imagen_jugador.png')

POSICION_INICIAL_X = 200
POSICION_INICIAL_y = 200
VELOCIDAD_JUGADOR = 5
