import os

ORIGEN_X_VENTANA = 200
ORIGEN_Y_VENTANA = 100
ANCHO_VENTANA = 800
ALTO_VENTANA = 600

ANCHO_JUGADOR = 30
ALTO_JUGADOR = 35
ANCHO_ESQUELETO = ANCHO_JUGADOR
ALTO_ESQUELETO = ALTO_JUGADOR
DIRECCION_SPRITE = os.path.join('utiles', 'imagen_jugador.png')
DIRECCION_SPRITE_ESQUELETO = os.path.join('utiles', 'esqueleto.png')

POSICION_INICIAL_X = 200
POSICION_INICIAL_y = 200
VELOCIDAD_JUGADOR = 5

# Area delimitada como spawn de enemigos en pixeles
AREA_MAX_ENEMIGOS_X = ANCHO_VENTANA - ANCHO_JUGADOR
AREA_MAX_ENEMIGOS_Y = ALTO_VENTANA - ALTO_JUGADOR

